apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: pazf/mongodb-express-rest-api-example:v2
          env:
            - name: ATLAS_URI
              value: mongodb://mongodb:27017/mydatabase
          ports:
            - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: my-app
spec:
  type: NodePort
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30505
  selector:
    app: server
